# Generated by Django 5.0.1 on 2024-01-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_email', models.CharField(max_length=70)),
                ('sub_type', models.CharField(default='Free', max_length=100)),
                ('sub_topic', models.TextField()),
                ('sub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
