# Generated by Django 5.0.1 on 2024-01-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sub',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
    ]
