# Generated by Django 5.0.1 on 2024-01-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sent_emails',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
