# Generated by Django 5.0.1 on 2024-01-24 14:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_sent_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sub_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='sub_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='sub_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
