# Generated by Django 5.0.1 on 2024-01-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_profile_sub_date_profile_sub_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sub_type',
        ),
        migrations.AlterField(
            model_name='profile',
            name='sub',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
