# Generated by Django 5.0.1 on 2024-01-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_profile_sub_alter_profile_sub_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sent_emails',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sub_end_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sub_start_date',
            field=models.DateTimeField(),
        ),
    ]
